feat(bash): add full language support (LSP, lint, format, DAP)

diff --git a/utils/install b/utils/install
--- a/utils/install
+++ b/utils/install
@@ -8,175 +8,175 @@ URL="https://github.com/neovim/neovim/releases/download"
 GITLAB="https://gitlab.com/elnox/neovim.git"
 NVMVERS="v0.40.1"
 NVIMDIR=(
-  ".local/nvim"
-  ".cache/nvim"
-  ".config/nvim"
-  ".local/share/nvim"
+    ".local/nvim"
+    ".cache/nvim"
+    ".config/nvim"
+    ".local/share/nvim"
 )
 FLAVORS=(
-  "init"
-  "master"
-  "local"
+    "init"
+    "master"
+    "local"
 )
 
 function usage() {
-  printf "usage: %s [options]\n\noptions:
+    printf "usage: %s [options]\n\noptions:
     --release   <stable || nightly || v0.10.3>
     --config    <init || master || local>
     --bakup     <bakup name>
     --restore   <bakup name>" "$0"
-  exit 0
+    exit 0
 }
 
 function bakup() {
-  echo "- Creating neovim backup ${BAK}"
+    echo "- Creating neovim backup ${BAK}"
 
-  for DIR in "${NVIMDIR[@]}"; do
-    if [[ -d ${HOME}/${DIR} ]]; then
-      [[ ! -d ${BAK}/${BAKUP}/${DIR} ]] && mkdir -p "${BAK}/${BAKUP}/${DIR}"
-      rsync -ar --delete "${HOME}/${DIR}/" "${BAK}/${BAKUP}/${DIR}"
-      echo "ok ${HOME}/${DIR} > ${BAK}/${BAKUP}/${DIR}"
-    fi
-  done
+    for DIR in "${NVIMDIR[@]}"; do
+        if [[ -d ${HOME}/${DIR} ]]; then
+            [[ ! -d ${BAK}/${BAKUP}/${DIR} ]] && mkdir -p "${BAK}/${BAKUP}/${DIR}"
+            rsync -ar --delete "${HOME}/${DIR}/" "${BAK}/${BAKUP}/${DIR}"
+            echo "ok ${HOME}/${DIR} > ${BAK}/${BAKUP}/${DIR}"
+        fi
+    done
 
-  echo "- Done: ls -la ${BAK}"
+    echo "- Done: ls -la ${BAK}"
 }
 
 function restore() {
-  STATUS=1
+    STATUS=1
 
-  echo "- Checking neovim bakup"
+    echo "- Checking neovim bakup"
 
-  for DIR in "${NVIMDIR[@]}"; do
-    if [[ ! -d ${BAK}/${RESTORE}/${DIR} ]]; then
-      echo "ko ${BAK}/${RESTORE}/${DIR}"
-      STATUS=0
+    for DIR in "${NVIMDIR[@]}"; do
+        if [[ ! -d ${BAK}/${RESTORE}/${DIR} ]]; then
+            echo "ko ${BAK}/${RESTORE}/${DIR}"
+            STATUS=0
+        fi
+    done
+
+    if [[ $STATUS -eq 0 ]]; then
+        echo "! skipping restore"
+        exit 1
     fi
-  done
 
-  if [[ $STATUS -eq 0 ]]; then
-    echo "! skipping restore"
-    exit 1
-  fi
+    for DIR in "${NVIMDIR[@]}"; do
+        rsync -ar --delete "${BAK}/${RESTORE}/${DIR}/" "$HOME/${DIR}"
+        echo "ok ${BAK}/${RESTORE}/${DIR}"
+    done
 
-  for DIR in "${NVIMDIR[@]}"; do
-    rsync -ar --delete "${BAK}/${RESTORE}/${DIR}/" "$HOME/${DIR}"
-    echo "ok ${BAK}/${RESTORE}/${DIR}"
-  done
+    echo "- Restoring neovim from bakup ${BAK}/${RESTORE}"
 
-  echo "- Restoring neovim from bakup ${BAK}/${RESTORE}"
-
-  exit 0
+    exit 0
 }
 
 function deploy() {
-  if [[ $REL =~ ^v[0-9]\.[0-9]+\.[0-9]$ ]]; then
-    echo "- Install neovim from tag $REL"
-  elif test "$REL" != "stable" && test "$REL" != "nightly"; then
-    usage
-  else
-    echo "- Install neovim from branch $REL"
-  fi
+    if [[ $REL =~ ^v[0-9]\.[0-9]+\.[0-9]$ ]]; then
+        echo "- Install neovim from tag $REL"
+    elif test "$REL" != "stable" && test "$REL" != "nightly"; then
+        usage
+    else
+        echo "- Install neovim from branch $REL"
+    fi
 
-  # ensure bin directory exists
-  if [ ! -d "$BIN" ]; then
-    echo "- creating $BIN directory, ensure $BIN is in your PATH"
-    mkdir "$BIN"
-  fi
+    # ensure bin directory exists
+    if [ ! -d "$BIN" ]; then
+        echo "- creating $BIN directory, ensure $BIN is in your PATH"
+        mkdir "$BIN"
+    fi
 
-  # cleanup existing neovim
-  [ -d "$HOME/.local/nvim" ] && rm -rf "$HOME/.local/nvim"
-  [ -L "$HOME/.local/bin/nvim" ] && rm -f "$HOME/.local/bin/nvim"
+    # cleanup existing neovim
+    [ -d "$HOME/.local/nvim" ] && rm -rf "$HOME/.local/nvim"
+    [ -L "$HOME/.local/bin/nvim" ] && rm -f "$HOME/.local/bin/nvim"
 
-  # create temp directory
-  TMPDIR=$(mktemp -d --tmpdir="$HOME" -t neovim-XXXXXXXXXX)
+    # create temp directory
+    TMPDIR=$(mktemp -d --tmpdir="$HOME" -t neovim-XXXXXXXXXX)
 
-  # install latest REL from appImage
-  wget "$URL/$REL/nvim-linux-x86_64.appimage" -O "$TMPDIR/nvim.appimage" 2>/dev/null ||
-    cp nvim/nvim.appimage "$TMPDIR"
-  chmod +x "$TMPDIR/nvim.appimage"
+    # install latest REL from appImage
+    wget "$URL/$REL/nvim-linux-x86_64.appimage" -O "$TMPDIR/nvim.appimage" 2> /dev/null \
+        || cp nvim/nvim.appimage "$TMPDIR"
+    chmod +x "$TMPDIR/nvim.appimage"
 
-  cd "$TMPDIR/" && ./nvim.appimage --appimage-extract &>/dev/null
-  mv "$TMPDIR/squashfs-root" "$HOME/.local/nvim"
+    cd "$TMPDIR/" && ./nvim.appimage --appimage-extract &> /dev/null
+    mv "$TMPDIR/squashfs-root" "$HOME/.local/nvim"
 
-  # cleanup temp
-  cd ~/ && rm -rf "$TMPDIR"
+    # cleanup temp
+    cd ~/ && rm -rf "$TMPDIR"
 
-  ln -s "$HOME/.local/nvim/usr/bin/nvim" "$HOME/.local/bin/nvim"
+    ln -s "$HOME/.local/nvim/usr/bin/nvim" "$HOME/.local/bin/nvim"
 }
 
 function config() {
-  if [[ ! ${FLAVORS[*]} =~ $FLAVOR ]]; then
-    usage
-  fi
+    if [[ ! ${FLAVORS[*]} =~ $FLAVOR ]]; then
+        usage
+    fi
 
-  # cleanup existing config
-  [ -d ~/.config/nvim ] && rm -rf ~/.config/nvim
-  if [[ "$FLAVOR" != "local" ]]; then
-    [ -d ~/.cache/nvim ] && rm -rf ~/.cache/nvim
-    [ -d ~/.local/share/nvim ] && rm -rf ~/.local/share/nvim
-  fi
+    # cleanup existing config
+    [ -d ~/.config/nvim ] && rm -rf ~/.config/nvim
+    if [[ "$FLAVOR" != "local" ]]; then
+        [ -d ~/.cache/nvim ] && rm -rf ~/.cache/nvim
+        [ -d ~/.local/share/nvim ] && rm -rf ~/.local/share/nvim
+    fi
 
-  # master / init / ...
-  if which node >/dev/null; then
-    echo "- Setup configuration $FLAVOR"
-  else
-    echo "! nodejs not found, either run one of these commands"
-    echo "! apt install npm nodejs --no-install-recommends"
-    echo "! curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/$NVMVERS/install.sh | $SHELL"
-    [ -z "$1" ] && exit 0
-  fi
-  if [[ "$FLAVOR" == "local" ]]; then
-    [[ -d "../nvim" ]] && cp -rf ../nvim ~/.config/
-  else
-    git clone $GITLAB ~/.config/nvim -q
-    cd ~/.config/nvim || exit
-    git fetch origin && git checkout "$FLAVOR"
-    nvim
-  fi
+    # master / init / ...
+    if which node > /dev/null; then
+        echo "- Setup configuration $FLAVOR"
+    else
+        echo "! nodejs not found, either run one of these commands"
+        echo "! apt install npm nodejs --no-install-recommends"
+        echo "! curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/$NVMVERS/install.sh | $SHELL"
+        [ -z "$1" ] && exit 0
+    fi
+    if [[ "$FLAVOR" == "local" ]]; then
+        [[ -d "../nvim" ]] && cp -rf ../nvim ~/.config/
+    else
+        git clone $GITLAB ~/.config/nvim -q
+        cd ~/.config/nvim || exit
+        git fetch origin && git checkout "$FLAVOR"
+        nvim
+    fi
 }
 
 function main() {
-  echo "*** Neovim installer"
+    echo "*** Neovim installer"
 
-  # parse args
-  [[ $# -eq 0 ]] && usage
-  while [[ $# -ne 0 ]]; do
-    arg="$1"
-    shift
-    case "$arg" in
-    --bakup)
-      BAKUP=$1
-      shift
-      ;;
-    --restore)
-      RESTORE=$1
-      shift
-      ;;
-    --release)
-      REL=$1
-      shift
-      ;;
-    --config)
-      FLAVOR=$1
-      shift
-      ;;
-    --help) usage ;;
-    *) [[ $arg =~ \-+.* ]] && usage "$arg unknown" ;;
-    esac
-  done
+    # parse args
+    [[ $# -eq 0 ]] && usage
+    while [[ $# -ne 0 ]]; do
+        arg="$1"
+        shift
+        case "$arg" in
+            --bakup)
+                BAKUP=$1
+                shift
+                ;;
+            --restore)
+                RESTORE=$1
+                shift
+                ;;
+            --release)
+                REL=$1
+                shift
+                ;;
+            --config)
+                FLAVOR=$1
+                shift
+                ;;
+            --help) usage ;;
+            *) [[ $arg =~ \-+.* ]] && usage "$arg unknown" ;;
+        esac
+    done
 
-  # bakup
-  [ -n "$BAKUP" ] && bakup
+    # bakup
+    [ -n "$BAKUP" ] && bakup
 
-  # restore
-  [ -n "$RESTORE" ] && restore
+    # restore
+    [ -n "$RESTORE" ] && restore
 
-  # install release
-  [ -n "$REL" ] && deploy
+    # install release
+    [ -n "$REL" ] && deploy
 
-  # config flavor
-  [ -n "$FLAVOR" ] && config
+    # config flavor
+    [ -n "$FLAVOR" ] && config
 }
 
 main "$@"
